apiVersion: v1
kind: Template
metadata:
  name: redis
  annotations:
    description: redis
    tags: node, poc, redis
objects:
# Deployment Configuration
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 302
    labels:
      app: redis
      stage: dev
      version: ${REDIS_VERSION}
    name: redis
  spec:
    replicas: 1
    strategy:
      type: Rolling
      rollingParams:
        intervalSeconds: 20
        maxUnavailable: 0%
        timeoutSeconds: 600
        maxSurge: 25%
    selector:
      app: redis
      deploymentconfig: redis
    template:
      metadata:
        labels:
          app: redis
          deploymentconfig: redis
      spec:
        containers:
          - env:
              - name: STAGE
                value: ${STAGE}
              - name: REDIS_URL
                value: ${REDIS_URL}
              - name: SERVER_PORT
                value: "6379"
              - name: SERVER_EXT
                value: "6379"
              - name: REDIS_URL
                value: "redis"
              - name: REDIS_PORT
                value: "6379"
            image: >-
              docker.bin.sbb.ch/pieni-poc/redis:${REDIS_VERSION}
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 5
              exec:
                command:
                  - cat
                  - /usr/local/etc/redis/liveness
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: redis
            ports:
              - containerPort: 6379
                protocol: TCP
            readinessProbe:
              failureThreshold: 5
              exec:
                command:
                  - cat
                  - /usr/local/etc/redis/health
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 1
                memory: 2Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: redis
    labels:
      app: redis
      env: pieni
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis
      deploymentconfig: redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
# Route
- apiVersion: v1
  kind: Route
  metadata:
    name: redis
    labels:
        app: redis
        env: dev
  spec:
    host: ${REDIS_URL}
    template:
      metadata:
        labels:
          name: redis
    to:
      kind: Service
      name: redis
    port:
      targetPort: 6379-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
# Parameters/ Environment
parameters:
  - name: STAGE
    description: "The stage: dev, inte, prod"
    required: true
    value: ${STAGE}
  - name: PIENI_POC_NAME
    description: "The name of your application"
    required: true
    value: "redis"
  - name: REDIS_VERSION
    description: "The version of the app to deploy"
    required: true
  - name: OPENSHIFT_BASE_DOMAIN
    description: "The OpenShift address of the current cluster"
    value: test04.otc-test.sbb.ch
    required: false
  - name: IMAGESTREAM_NAMESPACE
    description: "Artifactory Project where are built the image streams"
    value: redis
    required: true
  - name: REDIS_URL
    description: "URL for the Server and Route"
    value: pieni-redis.app.test04.otc-test.sbb.ch
    required: true